'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
'''
n = 4000000
evensum = 0
def fibIter(cap):
    global evensum
    evensum = 0
    tokens = [1,2]
    while (tokens[-1] < cap):
        evensum += tokens[-1]
        for i in range(3):
            tokens.append(tokens[-1] + tokens[-2])   
fibIter(n)
print(evensum)
